package com.lewis.zhaopin.mapper;

import com.lewis.zhaopin.entity.Jianli;
import java.util.List;

public interface JianliMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianli
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianli
     *
     * @mbg.generated
     */
    int insert(Jianli record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianli
     *
     * @mbg.generated
     */
    Jianli selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianli
     *
     * @mbg.generated
     */
    List<Jianli> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianli
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Jianli record);
}