package com.lewis.zhaopin.mapper;

import com.lewis.zhaopin.entity.Luntan;
import java.util.List;

public interface LuntanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luntan
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luntan
     *
     * @mbg.generated
     */
    int insert(Luntan record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luntan
     *
     * @mbg.generated
     */
    Luntan selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luntan
     *
     * @mbg.generated
     */
    List<Luntan> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table luntan
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Luntan record);
}