package com.lewis.zhaopin.mapper;

import com.lewis.zhaopin.entity.Toudi;
import java.util.List;

public interface ToudiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toudi
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toudi
     *
     * @mbg.generated
     */
    int insert(Toudi record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toudi
     *
     * @mbg.generated
     */
    Toudi selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toudi
     *
     * @mbg.generated
     */
    List<Toudi> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table toudi
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Toudi record);
}