package com.lewis.zhaopin.entity;

import java.io.Serializable;

public class Jianli implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.img
     *
     * @mbg.generated
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.sex
     *
     * @mbg.generated
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.age
     *
     * @mbg.generated
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.xueli
     *
     * @mbg.generated
     */
    private String xueli;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.school
     *
     * @mbg.generated
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.jingyan
     *
     * @mbg.generated
     */
    private String jingyan;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.position
     *
     * @mbg.generated
     */
    private String position;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.jingli
     *
     * @mbg.generated
     */
    private String jingli;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.moeny
     *
     * @mbg.generated
     */
    private String moeny;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.pingjia
     *
     * @mbg.generated
     */
    private String pingjia;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jianli.uid
     *
     * @mbg.generated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table jianli
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.id
     *
     * @return the value of jianli.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.id
     *
     * @param id the value for jianli.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.img
     *
     * @return the value of jianli.img
     *
     * @mbg.generated
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.img
     *
     * @param img the value for jianli.img
     *
     * @mbg.generated
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.name
     *
     * @return the value of jianli.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.name
     *
     * @param name the value for jianli.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.sex
     *
     * @return the value of jianli.sex
     *
     * @mbg.generated
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.sex
     *
     * @param sex the value for jianli.sex
     *
     * @mbg.generated
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.age
     *
     * @return the value of jianli.age
     *
     * @mbg.generated
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.age
     *
     * @param age the value for jianli.age
     *
     * @mbg.generated
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.xueli
     *
     * @return the value of jianli.xueli
     *
     * @mbg.generated
     */
    public String getXueli() {
        return xueli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.xueli
     *
     * @param xueli the value for jianli.xueli
     *
     * @mbg.generated
     */
    public void setXueli(String xueli) {
        this.xueli = xueli == null ? null : xueli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.school
     *
     * @return the value of jianli.school
     *
     * @mbg.generated
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.school
     *
     * @param school the value for jianli.school
     *
     * @mbg.generated
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.jingyan
     *
     * @return the value of jianli.jingyan
     *
     * @mbg.generated
     */
    public String getJingyan() {
        return jingyan;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.jingyan
     *
     * @param jingyan the value for jianli.jingyan
     *
     * @mbg.generated
     */
    public void setJingyan(String jingyan) {
        this.jingyan = jingyan == null ? null : jingyan.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.phone
     *
     * @return the value of jianli.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.phone
     *
     * @param phone the value for jianli.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.address
     *
     * @return the value of jianli.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.address
     *
     * @param address the value for jianli.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.position
     *
     * @return the value of jianli.position
     *
     * @mbg.generated
     */
    public String getPosition() {
        return position;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.position
     *
     * @param position the value for jianli.position
     *
     * @mbg.generated
     */
    public void setPosition(String position) {
        this.position = position == null ? null : position.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.jingli
     *
     * @return the value of jianli.jingli
     *
     * @mbg.generated
     */
    public String getJingli() {
        return jingli;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.jingli
     *
     * @param jingli the value for jianli.jingli
     *
     * @mbg.generated
     */
    public void setJingli(String jingli) {
        this.jingli = jingli == null ? null : jingli.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.moeny
     *
     * @return the value of jianli.moeny
     *
     * @mbg.generated
     */
    public String getMoeny() {
        return moeny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.moeny
     *
     * @param moeny the value for jianli.moeny
     *
     * @mbg.generated
     */
    public void setMoeny(String moeny) {
        this.moeny = moeny == null ? null : moeny.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.pingjia
     *
     * @return the value of jianli.pingjia
     *
     * @mbg.generated
     */
    public String getPingjia() {
        return pingjia;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.pingjia
     *
     * @param pingjia the value for jianli.pingjia
     *
     * @mbg.generated
     */
    public void setPingjia(String pingjia) {
        this.pingjia = pingjia == null ? null : pingjia.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jianli.uid
     *
     * @return the value of jianli.uid
     *
     * @mbg.generated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jianli.uid
     *
     * @param uid the value for jianli.uid
     *
     * @mbg.generated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table jianli
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", img=").append(img);
        sb.append(", name=").append(name);
        sb.append(", sex=").append(sex);
        sb.append(", age=").append(age);
        sb.append(", xueli=").append(xueli);
        sb.append(", school=").append(school);
        sb.append(", jingyan=").append(jingyan);
        sb.append(", phone=").append(phone);
        sb.append(", address=").append(address);
        sb.append(", position=").append(position);
        sb.append(", jingli=").append(jingli);
        sb.append(", moeny=").append(moeny);
        sb.append(", pingjia=").append(pingjia);
        sb.append(", uid=").append(uid);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}